# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GetWeatherData
                                 A QGIS plugin
 This plugin creates a layer containing weather data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-30
        copyright            : (C) 2022 by Ufuk Emre Yıldırım
        email                : emretus@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GetWeatherData class from file GetWeatherData.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .get_weather_data import GetWeatherData
    return GetWeatherData(iface)
